### ISSUE TITLE
[feature/question] get coverage profiles

### ISSUE THREAD

**Issue by cdiener** [seqan/slimm#25]
Hi, first of all congrats and thanks for SLIMM, awesome software. I was wondering if there is a way to get the the actual coverage profiles for individual species across the bins. SLIMM is pretty fast so I would like to use it to do something like in https://www.ncbi.nlm.nih.gov/pubmed/26229116. From a quick scan of the code base it looks like there is currently not an option for that, but the information is stored in the reference contig.

If I wanted the the coverage profiles for reads after they have been assigned to the most likely reference I would use the the `uniq_cov2.bin_heights`, correct?

**Comment by temehi** [comment]
HI, Thanks for using SLIMM. 

You are right about `uniq_cov2.bin_heights`. But this will be a very sparse coverage compared to `cov.bin_heights`

I can add an option to SLIMM (`--coverage-output`) to print out the coverage profiles per reference genomes, comma-separated integers. Would that work?

**Comment by temehi** [comment]
Could you please build and check the branch [coverage_profile](https://github.com/temehi/slimm/tree/coverage_profile) on my repo? I implemented the option to output three coverage profiles.

1. The original coverage by all the reads( non-unique) 
2. The original coverage by unique reads
3. The corrected coverage by recomputed unique reads

The profiles are writen only for the references that pass the threshold. 
I will merge it with the main repository and release a new version once it's well tested.

Cheers!

**Comment by cdiener** [comment]
Works like a charm.

Thanks! Will play round with those profiles for a while.

**Comment by your-highness** [comment]
Hi Temesgen,

I would like to re-open this topic because my questions pertain to this request:

> 1. The original coverage by all the reads( non-unique)
> 2. The original coverage by unique reads
> 3. The corrected coverage by recomputed unique reads

_The extension for the original coverage by all reads is "_coverge.tsv"?_
_The extension for the original coverage by unique reads is "_uniq_coverge.tsv"?_
_The extension for the original coverage by recomputed unique reads is "_uniq_coverge2.tsv"?_

*Another question related:*
The sum of reads reported in column "read_counts" of file "_profile.tsv" should correspond to the sum of coverage. However, my values differ:

- _profile.tsv: 28,721,244
- _coverage.tsv: 31,321,156
- _uniq_coverge.tsv: 90,779
- _uniq_coverge2.tsv: 25,001,034

_Can you please explain?_

Thanks!

**Comment by your-highness** [comment]
@temehi Can you please answer the following questions regarding the output files:

 - The extension for the original coverage by all reads is "coverge.tsv"?
 - The extension for the original coverage by unique reads is "uniq_coverge.tsv"?
 - The extension for the original coverage by recomputed unique reads is "uniq_coverge2.tsv"?

Thank you!

**Comment by temehi** [comment]
@your-highness 

> * The extension for the original coverage by all reads is "coverge.tsv"?
> * The extension for the original coverage by unique reads is "uniq_coverge.tsv"?
> * The extension for the original coverage by recomputed unique reads is "uniq_coverge2.tsv"?

all is correct!

**Comment by your-highness** [comment]
Thanks @temehi 

_Another question related:_
The sum of reads reported in column "read_counts" of file "_profile.tsv" should correspond to the sum of coverage. However, my values differ:

_profile.tsv: 28,721,244
_coverage.tsv: 31,321,156
_uniq_coverge.tsv: 90,779
_uniq_coverge2.tsv: 25,001,034

_Can you please explain?_

Thanks again!

**Comment by temehi** [comment]
> The sum of reads reported in column "read_counts" of file "_profile.tsv" should correspond to the sum of coverage. However, my values differ:

That is expected :) What you have in:
-  `_profile.tsv` is the sum of reads that made it at any level of the taxonomy
-  `_coverage.tsv` is the sum of reads that makes the coverage of every genome, including those to be discarded. in other words, this is the number of mapped reads.
-  `_uniq_coverge.tsv` is the same as above except this is the coverage by original unique reads.
-  `_uniq_coverge2.tsv` is the same as above except here we recalculated read-uniqueness after discarding some genomes due to their bad coverage

**Comment by your-highness** [comment]
Ok. Thanks for the clarification @temehi !

**Which type of counts, _e.g._ uniq1 or uniq2, are given in the file `_profile.tsv`?** Given the numbers above `_profile.tsv` does contain 15% more reads than `_uniq_coverge2.tsv`. In principle, I think that "the sum of reads that made it at any level of the taxonomy" in `_profile.tsv` should _somewhat_ correspond to the number of total reads aligned to the index.

The file `_raw.tsv` contains all information for all sequences in the index (except profiles). I see that `_coverge.tsv`, `_uniq_coverge.tsv` and `_uniq_coverge2.tsv` contain only those entries where `uniq2_reads_count` in `_raw.tsv` is > 0 .

Mentioning @agakrawczyk

**Comment by temehi** [comment]
The 15% more reads in `_profile.tsv` could be because of two reasons.

1. In profiles we could have two references under a species or something. So even though a read is not unique to a reference it could be unique for a species. That is if all reference genomes sharing the read belong to the same species.

2. There is there unknown_  row in the profiles this are also non unique reads which are assigned  to the LCA

**Comment by your-highness** [comment]
> The 15% more reads in `_profile.tsv` could be because of two reasons.
> 
> 1. In profiles we could have two references under a species or something. So even though a read is not unique to a reference it could be unique for a species. That is if all reference genomes sharing the read belong to the same species.

I see that a species-based uniqueness is used in the profile which is perfectly reasonable!

> 2. There is there unknown_  row in the profiles this are also non unique reads which are assigned  to the LCA

The last row in `_profile.tsv` is named `k__unknown_superkingdom|p__unknown_phylum|c__unknown_class|o__unknown_order|f__unknown_family|g__unknown_genus|s__unknown_species`. 
_It contains all LCAs that were identified on a level higher than the required rank (as given by `--rank`), correct?_ See also #36 

Mentioning @pmenzel

**Comment by temehi** [comment]
> The last row in `_profile.tsv` is named `k__unknown_superkingdom|p__unknown_phylum|c__unknown_class|o__unknown_order|f__unknown_family|g__unknown_genus|s__unknown_species`.
> _It contains all LCAs that were identified on a level higher than the required rank (as given by `--rank`), correct?_ See also #36

That is correct! This row contains reads that couldn't be identified all the way to the superkingdom level.
We could also have something like:
```
species  91347 k_Bacteria|p_Proteobacteria|c_Gammaproteobacteria|o_Enterobacterales|f_Enterobacteriaceae|g_unknown_genus|s__unknown_species       5.01    109321
```
When 5% of the reads are not unique at the species level but they are unique at the family level and belong to family Enterobacteriaceae.

**Comment by temehi** [comment]
May I close this issue @your-highness? ☺️
