### ISSUE TITLE
various questions

### ISSUE THREAD

**Issue by fconstancias** [seqan/slimm#29]
Thanks a lot for your efforts developing this promising tool.

I would like to use SLIMM to characterize microbial species  composition from various metagenomes.
I do not have any issue to report, I have just some questions :

- Is it a good idea to try bowtie2 `local` alignement parameters? Is there any rationale to set the `-k` value such as metagenomes _a priori_ diversity or size ?
- Do you have any details/guidances regarding the `-w` and `--cov-cut-off` parameters ?
- Does the `_profile.tsv` output report taxa abundance (_i.e._, genome size normalized) or is it just the percentage of reads?
- Is there any easy way to merge all the `_profile.tsv` or  generate a biom file species table which could be easily loaded in R phyloseq?
- I would like to prepare a custom database using the 'curated' database created by the [DTU](https://www.nature.com/articles/s41598-018-22416-4), I have made some tests on two sequences and the header seems to be not properly formatted.

```
[MSG] getting accessions numbers from fasta file ...
[MSG] mapping accessions to taxaid ...
[WARNING!] 1 accessions (kraken:taxid, ...) were not mapped to taxaid.
[WARNING!] Take a look at slimm_db_custom.missed file for a complete list.
[WARNING!] Try including the more ACCESSION2TAXAID MAP FILE (e.g. dead_nucl.accession2taxid)
[MSG] loading nodes and names mappings from files ...
[MSG] getting taxonomic linages and resolving names ...
[@cc2-n23 SLIMM]$ tail slimm_db_custom.missed
kraken:taxid
```
`
>kraken:taxid|556484|NC_011669.1|1 Phaeodactylum tricornutum CCAP 1055/1 chromosome 1, whole genome shotgun sequence
`
If you have an idea how to fix this?

Thanks a lot for your help and efforts developing SLIMM.

Cheers,

Flo

**Comment by temehi** [comment]
Thanks for checking out SLIMM!

I will try two answer your questions one at a time 
> Is it a good idea to try bowtie2 local alignment parameters? Is there any rationale to set the -k value such as metagenomes a priori diversity or size?

The only important thing is not to miss an alignment because of the randomness of the read mapper. In metagenomics, reads will map to a multitude of locations due to similarity among the reference genomes (consider multiple references under a genus). Since SLIMM tries to resolve this later in non-random fashion, assigning a larger value to `-k` parameter of bowtie2 will broaden the choice of alignments for SLIMM. 

>Do you have any details/guidances regarding the -w and --cov-cut-off parameters?

`--bin-width` is set to the average read length by default. I would leave it as it is. the only reason to increase `--bin-width` is to make SLIMM run even faster and make it use less RAM. `--cov-cut-off `, on the other hand, influences greatly the number of organisms detected, specifically the low abundance ones. bigger `--cov-cut-off ` will give you a more stringent filter, but you might miss some low abundant organisms. The benchmarking on the paper is done with the default value.


>Does the _profile.tsv output report taxa abundance (i.e., genome size normalized) or is it just the percentage of reads?

Yes it is normalized by the **avarage** genome size of  reference genomes.

> Is there any easy way to merge all the _profile.tsv or generate a biom file species table which could be easily loaded in R phyloseq?

Not at the moment. A pull request is apreciated :)

>I would like to prepare a custom database using the 'curated' database created by the DTU, I have made some tests on two sequences and the header seems to be not properly formatted.
[MSG] getting accessions numbers from fasta file ...
[MSG] mapping accessions to taxaid ...
[WARNING!] 1 accessions (kraken:taxid, ...) were not mapped to taxaid.
[WARNING!] Take a look at slimm_db_custom.missed file for a complete list.
[WARNING!] Try including the more ACCESSION2TAXAID MAP FILE (e.g. dead_nucl.accession2taxid)
[MSG] loading nodes and names mappings from files ...
[MSG] getting taxonomic linages and resolving names ...
[@cc2-n23 SLIMM]$ tail slimm_db_custom.missed
kraken:taxid
`
kraken:taxid|556484|NC_011669.1|1 Phaeodactylum tricornutum CCAP 1055/1 chromosome 1, whole genome shotgun sequence
`
If you have an idea how to fix this?

The custum database you have has the accession_id in the middle. SLIMM's database builder expectes the accession_id at the begining as it is the case for downloaded genomes. In this case the text  `kraken:taxid` is considerd as an accession. One possiblity for you is to parse your fatsa files and rearange the headers accordingly. 

the fasta headers should look something like:
```
>NC_011669.1|kraken:taxid|556484|NC_011669.1|1 Phaeodactylum tricornutum CCAP 1055/1 chromosome 1, whole genome shotgun sequence
```

**Comment by temehi** [comment]
>I do not have any issue to report, I have just some questions :

Hope my reply helped. :) I will close the issue now.
