### ISSUE TITLE
can't download viral bowtie2 index

### ISSUE THREAD

**Issue by tigerxu** [seqan/slimm#35]
Hi, 

I found the following command not work

wget https://ftp.mi.fu-berlin.de/pub/dadi/slimm/V_genomes_indices_20180924_bowtie.zip

$ wget https://ftp.mi.fu-berlin.de/pub/dadi/slimm/V_genomes_indices_20180924_bowtie.zip
--2019-01-16 11:26:15--  https://ftp.mi.fu-berlin.de/pub/dadi/slimm/V_genomes_indices_20180924_bowtie.zip
Resolving ftp.mi.fu-berlin.de... 160.45.117.8
Connecting to ftp.mi.fu-berlin.de|160.45.117.8|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-16 11:26:16 ERROR 404: Not Found.

Could you help to look at this problem?

Many thanks

Zhuofei

**Comment by temehi** [comment]
Hello Zhuofei,

I have intentionally deleted the viral genomes database, due to the confusion it created while interpreting the resulting taxonomic profiles. With that database, one can only detect viruses and they are a tiny fraction of any microbial community.

But, I have forgotten to update the wiki accordingly. The viral databases were in the tutorial because they are easy to download as they are very small. I will sort that out soon.

In the meantime, you can use the complete database (~30G of download) from,
https://ftp.mi.fu-berlin.de/pub/dadi/slimm/ABVF_SP_CMP_genomes.bowtie2.zip

together with the slimm database:
https://ftp.mi.fu-berlin.de/pub/dadi/slimm/ABVF_SP_CMP_genomes.sldb

Cheers,
Temesgen

**Comment by temehi** [comment]
closing the issue due to inactivity!
